config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'recipes#index'
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    resources :recipe_foods, only: [:index, :new, :create]
  end
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :public_recipes, only: [:index]
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, foreign_key: 'recipe_id'
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 250 }

  def return_recipe_foods
    this.recipe_foods.each do |recipe_food|
      food = recipe_food.food
      food[:quantity] = recipe_food.quantity
      @required_foods << food
    end
  end

  def total_food_items
    recipe_foods.count
  end

  def total_price
    total_price = 0
    recipe_foods.each do |recipe_food|
      total_price += recipe_food.quantity * recipe_food.food.price
    end
    total_price
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes([:food])
  end

  def new
    recipe = Recipe.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: } }
    end
  end

  def create
    recipe = params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
    new_recipe = Recipe.new(recipe)
    new_recipe.user = current_user
    respond_to do |format|
      format.html do
        if new_recipe.save
          flash[:notice] = 'Recipe created successfully'
          redirect_to recipes_path
        else
          flash.now[:alert] = 'Recipe creation failed'
          render :new, locals: { recipe: }
        end
      end
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    respond_to do |format|
      format.html do
        flash[:notice] = 'Recipe deleted successfully'
        redirect_to recipes_path
      end
    end
  end

  # def destroy
  #   @recipe = Recipe.find(params[:id])
  #   @recipe.destroy
  #   redirect_to recipes_path, notice: 'Recipe deleted successfully'
  # end
end

app/views/recipes/index.html.erb
<section class="container text-center">
  <h1 class="mb-5">
    Your recipes
  </h1>
  <%= link_to new_recipe_path do %>
    <button class="btn btn-primary mb-3">Add Recipe</button>
  <% end %>

  <div>
    <% @recipes.each do |recipe| %>
    <div class="row border border-dark border-2 rounded align-items-start m-4 p-4">

      <div class="col">
        <%= link_to recipe_path(recipe.id) do %>
          <h4><%= recipe.name %></h4>
        <% end %>
        
        <%= form_for(recipe, method: :delete) do |f| %>
          <%= submit_tag "Delete", data: { confirm: "Are you sure?" } %>
        <% end %>
      </div>

      <div class="col">
       <p><%= recipe.description %></p>
      </div>

    </div>
    <% end %>
  </div>
</section>

app/views/recipes/new.html.erb
<section class="container">
    <h1>Add Recipe</h1>
    <%= form_with model: recipe, method: :post, url: recipes_path, local: true, scope: :recipe do |form| %> 
        <div class="form-group mb-3">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
            <%= form.label :preparation_time %>
            <%= form.text_field :preparation_time, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
            <%= form.label :cooking_time %>
            <%= form.text_field :cooking_time, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
            <%= form.label :description %>
            <%= form.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :question, "Do you want this recipe to be public?" %>
          <%= form.radio_button :public, true %>
          <%= form.label :public, "Yes" %>
          <%= form.radio_button :public, false %>
          <%= form.label :age_adult, "No" %>
        </div>
        
        <% if flash.now[:alert] %>
            <p class="alert"><%= flash[:alert] %></p>
        <% end %>
        <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
</section>

app/views/recipes/show.html.erb
<section class="container text-center">
  <h1 class="mb-5">
    <%= @recipe.name %>
  </h1>

  <div class="container text-start">
    <div class="container text-end">This recipe is 
      <% if @recipe.public %>
        <p class="one">PUBLIC</p>
      <% else %>
        <p class="two">PRIVATE</p>
      <% end %>
    </div>
    <p>Preparation time: <%= @recipe.preparation_time %></p>
    <p>Cooking time: <%= @recipe.cooking_time %></p>
    <p>Steps go here...</p>
  </div>

  <div class="container text-start mt-3 mb-3">
    <% if @recipe.user_id == current_user.id %>
      <%= link_to shopping_list_path do %>
        <button class="btn btn-primary me-5">Generate shopping list</button>
      <% end %>
      <%= link_to new_recipe_recipe_food_path(@recipe.id) do %>
        <button class="btn btn-primary">Add ingredient</button>
      <% end %>
    <% end %>
  </div>

  <table class="table table-striped table-hover mt-5">
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
    <% @recipe_foods.each do |recipe_food| %>
      <%= render partial: "shared/recipe_ingredients", locals: { recipe_food: recipe_food } %>
    <% end %>
  </table>

</section>