config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'recipes#index'
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    resources :recipe_foods, only: [:index, :new, :create]
  end
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :public_recipes, only: [:index]
  
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-5">
  <a class="navbar-brand" href="#">My Recipes</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item mx-3">
        <%= link_to "Public Recipes", public_recipes_path, class: "nav-link #{'active' if current_page?(root_path)}" %>
      </li>
      <li class="nav-item mx-3">
        <%= link_to "Your Recipes", recipes_path, class: "nav-link #{'active' if current_page?(recipes_path)}" %>
      </li>
      <li class="nav-item mx-3">
        <%= link_to "Food List", foods_path, class: "nav-link #{'active' if current_page?(foods_path)}" %>
      </li>
    </ul>
    <%if user_signed_in? %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/shared/_recipe_ingredients.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= recipe_food.quantity %></td>
  <td><%= recipe_food.food.price %></td>
  <td class="text-muted">
    <span class="me-5 text-decoration-underline">Modify  </span>
    <span class="text-decoration-underline">  Remove</span>
  </td>
</tr>