config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'recipes#index'
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    resources :recipe_foods, only: [:index, :new, :create]
  end
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :public_recipes, only: [:index]
  
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, foreign_key: 'food_id'
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 250 }
  validates :price, presence: true, numericality: { only_integer: true }
  validates :quantity, presence: true, numericality: { only_integer: true }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def new
    new_food = Food.new
    respond_to do |format|
      format.html { render :new, locals: { food: new_food } }
    end
  end

  def create
    food_params = params.require(:new_food).permit(:name, :measurement_unit, :price, :quantity)
    food = Food.new(food_params)
    food.user = current_user
    respond_to do |format|
      format.html do
        if food.save
          flash[:notice] = 'Food created successfully'
          redirect_to foods_path
        else
          Rails.logger.error(food.errors.full_messages)
          flash.now[:alert] = 'Food creation failed'
          render :new, locals: { food: }
        end
      end
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    respond_to do |format|
      format.html do
        flash[:notice] = 'Food deleted successfully'
        redirect_to foods_path
      end
    end
  end
end

app/views/foods/index.html.erb
<div class="foods-container px-5">
    <div class="add-food-container">
        <a href="<%= new_food_path %>">
         <button class="btn btn-primary">Add Food</button>
         </a>
    </div>
    <div class="foods-list">
        <table class="table table-striped">
            <thead>
                <th>Name</th>
                <th>Measurement Unit</th>
                <th>Unit Price</th>
                <th>Actions</th>
            </thead>
            <tbody>
                <% @foods.each do |food| %>
                    <tr>
                        <td><%= food.name %></td>
                        <td><%= food.measurement_unit %></td>
                        <td><%= food.price %></td>
                        <td>
                            <%= form_for(food, method: :delete) do |f| %>
                                <%= submit_tag "Delete", data: { confirm: "Are you sure?" } %>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/foods/new.html.erb
<div class="container col-6">
    <h1>Add Food</h1>
    <%= form_with model: food, method: :post, url: foods_path, local: true, scope: :new_food do |form| %> 
        <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :measurement_unit %>
            <%= form.text_field :measurement_unit, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :price %>
            <%= form.text_field :price, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :quantity %>
            <%= form.text_field :quantity, class: "form-control" %>
        </div>
        <% if flash.now[:alert] %>
            <p class="alert"><%= flash[:alert] %></p>
        <% end %>
        <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
</div>