config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'recipes#index'
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    resources :recipe_foods, only: [:index, :new, :create]
  end
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :public_recipes, only: [:index]
  
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'

  validates :quantity, presence: true, numericality: { only_integer: true }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index; end

  def new
    @foods = Food.where(user_id: current_user.id)
    @recipe = Recipe.find(params[:recipe_id])
    recipe_food = RecipeFood.new
    respond_to do |format|
      format.html { render :new, locals: { recipe_food: } }
    end
  end

  def create
    new_recipe_food = RecipeFood.new(recipe_id: params[:recipe_id], food_id: params[:recipe_food][:food_id],
                                     quantity: params[:recipe_food][:quantity])
    respond_to do |format|
      format.html do
        if new_recipe_food.save
          flash[:notice] = 'Ingredient added successfully'
          redirect_to recipe_path(new_recipe_food.recipe_id)
        else
          flash.now[:alert] = 'Ingredient creation failed'
          render :new, locals: { recipe: }
        end
      end
    end
  end
end

app/views/recipe_foods/new.html.erb
<section class="container">
  <h1 class="mb-5">Add ingredient to recipe</h1>
  <%= form_with model: recipe_food, method: :post, url: recipe_recipe_foods_path(@recipe.id), local: true, scope: :recipe_food do |form| %> 
    <div class="form-group mb-3">
      <%= form.label :question, "Select the ingredient you want to add to the recipe" %>
      <br>
      <% @foods.each do |food| %>
        <div class="form-check form-check-inline d-flex">
        <%= form.radio_button :food_id, food.id %>
        <%= form.label :food_id, food.name %>
        <br>
        </div>
      <% end %>
    </div>
    <div class="form-group mb-3">
      <%= form.label :quantity %><br>
      <%= form.number_field :quantity %>
    </div>
    <%= form.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</section>